#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "config_app"
name = "Config panel"
description.en = "Dummy app to test config panel"

version = "1.0~ynh1"

maintainers = ["ljf"]

[upstream]
license = "GPL-3+"

[integration]
yunohost = ">= 4.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
