#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=2

# Remove the dedicated NGINX config
ynh_remove_nginx_config

ynh_script_progression --message="Removing custom files..." --weight=2

sudo rm -f /etc/importantfile
