#!/bin/bash
set -eu

# Source app helpers
source /usr/share/yunohost/helpers

restore_dir=$1
app=$2

# Get old parameter of the app
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
helper_to_test=$(ynh_app_setting_get $app helper_to_test)

# Test the 2 alternatives to restore
if [ "$helper_to_test" == "ynh_restore" ]; then
    # Restore all backuped files
    ynh_restore
else
    # Restore www directory
    ynh_restore_file /var/www/$app

    # Restore nginx conf
    ynh_restore_file /etc/nginx/conf.d/$domain.d/$app.conf

    # Restore custom file (with different source/destinations)
    ynh_restore_file /etc/yoloswag /etc/importantfile
fi

# Restore the database 
db_user=$app
db_pwd=$(ynh_app_setting_get $app mysqlpwd)
ynh_mysql_create_db $db_user $db_user $db_pwd
sudo su -c "mysql -u $db_user -p$db_pwd $app < ${restore_dir}/db.sql"

# Reload/reconfigure services
sudo service nginx reload
sudo yunohost app ssowatconf
