#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

# Test the 2 alternatives to restore
if [ "$helper_to_test" == "ynh_restore" ]; then
    # Restore all backed up files
    ynh_restore
else
    ynh_restore_file "$install_dir"
    chown -R "$app:www-data" "$install_dir"

    ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

    ynh_restore_file /etc/yoloswag /etc/importantfile

fi

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
ynh_script_progression --message="Restoring the MySQL database..." --weight=1

ynh_mysql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./db.sql

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
