#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "break_yo_system"
name = "Break your system!"
description.en = "That's a nice server you have here ... would be a shame if somebody was to ... break it !"

version = "2.0~ynh1"

maintainers = ["Aleks"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 12.0"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    example = "/break_yo_system"
    default = "/break_yo_system"

    [install.breakwhat]
    type = "select"
    ask.en = "What script to break"
    default = "none"
    choices.none = "None"
    choices.install = "Install script"
    choices.remove = "Remove script"
    choices.upgrade = "Upgrade script"
    choices.everything = "Every script"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"
