#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "permissions_app"
name = "Permissions Test"
description.en = "Dummy app to test permissions"

version = "1.0~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "Apache-2.0"

[integration]
yunohost = ">= 12.1"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.domain_2]
    ask.en = "Choose a second domain for permissions_app"
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/permissions_app"

    [install.init_main_permission]
    help.en = "A private app will only be accessible to logged-in users"
    help.fr = "Une app privée sera seulement accessible aux utilisateurs connectés"
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.protected = true

    dev.url = "/dev"
    dev.auth_header = false

    test.protected = false

    trybreakssowat_1.url = "re:/break[a-z]*/"
    trybreakssowat_1.show_tile = true

    trybreakssowat_2.show_tile = true
