#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "change_url_app"
name = "Change Url"
description.en = "Dummy app to test change_url"

version = "1.0~ynh1"

maintainers = ["bram"]

[upstream]
license = "GPL-3+"

[integration]
yunohost = ">= 12.1"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    example = "domain.org"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    example = "/"
    default = "/"

    [install.init_main_permission]
    help.en = "A private app will only be accessible to logged-in users"
    help.fr = "Une app privée sera seulement accessible aux utilisateurs connectés"
    type = "group"
    default = "visitors"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
