#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "full_domain_app"
name = "Full domain app"
description.en = "App to test the install of full domain apps"

version = "2.0~ynh1"

maintainers = ["aleks"]

[upstream]
license = "GPL-3.0"
website = "http://hextris.github.io/"
demo = "https://hextris.io/"
code = "https://github.com/Hextris/Hextris"

[integration]
yunohost = ">= 12.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64/armel), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant"
sso = "?" # FIXME: replace with true, false, or "not_relevant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.breakwhat]
    type = "string"
    ask.en = "What script to break"
    default = "none"
    choices.none = "None"
    choices.install = "Install script"
    choices.remove = "Remove script"
    choices.upgrade = "Upgrade script"
    choices.everything = "Every script"


[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"
