#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Nothing to do ... Permission using relative urls don't need to be changed, only the domain/path setting (handled in the core)
