#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# SET CUSTOM PERMISSIONS
#=================================================
ynh_script_progression --message="Setting up permissions..." --weight=1


ynh_permission_update --permission "admin" --add "$admin"

if [[ "$domain" == "$domain_2" ]]; then
    url_for_domain_2=""
else
    url_for_domain_2="$domain_2/"
fi

ynh_permission_url --permission "dev" --add_url "/dev2" "/otherdev" "$url_for_domain_2"
