#!/bin/bash

#=================================================
# GENERIC START
#=================================================

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Stop script if errors
ynh_abort_if_errors

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path_url=$(ynh_normalize_url_path $YNH_APP_ARG_PATH)
admin_user=$YNH_APP_ARG_ADMIN

# Check domain/path availability
ynh_webpath_available $domain $path_url || ynh_die "$domain$path_url is not available, please use an other domain or path."
ynh_webpath_register $app $domain $path_url

ynh_permission_create --app $app --permission "admin" --defaultdisallow --url "$domain$path_url/admin"
yunohost user permission add $app -p "admin" -u $admin_user

ynh_permission_create --app $app --permission "dev"
ynh_permission_add_path --app $app --permission "dev" --url "$domain$path_url/dev"
