packaging_format = 2

id = "hellopy"
name = "hellopy"

description.en = "Dummy app"

version = "1.0~ynh1"

maintainers = ["Aleks"]

[upstream]
license = "WTFPL"

[integration]
yunohost = '>= 11.2'
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
